### ISSUE TITLE
DANGER - DO NOT DOWNLOAD (WILL GET YOU KILLED IRL)

### ISSUE THREAD

**Issue by YeahOMA** [TrvsF/wurstplus-two#101]
DO NOT DOWNLOAD!
THIS IS MALWARE!
WIFIES POSTED A VIDEO ABOUT THE PHOBOS CLIENT AND WURST PLUS TWO THIS IS WURST PLUS TWO! IT WILL STEAL YOUR CREDIT CARD INFO DISCORD TOKEN AND YOUR EMAIL AND PASSWORD!!!

WIFIES SAID SOMETHING ABOUT A TROJAN HORSE COMING INTO YOUR HOUSE AND KILLING YOU DO NOT DOWNLOAD.

REPORT THIS TO THE FBI

**Comment by TrvsF** [comment]
> WIFIES SAID SOMETHING ABOUT A TROJAN HORSE COMING INTO YOUR HOUSE AND KILLING YOU DO NOT DOWNLOAD.I

i think you misheard, it's actually me that crawls through ur webcam and kills you
please do your research before opening an issue

**Comment by YeahOMA** [comment]
WHAT

**Comment by Mskeen000** [comment]
Im not sure if this is troll or not
