### ISSUE TITLE
some issues ;)

### ISSUE THREAD

**Issue by nekounderscore** [TrvsF/wurstplus-two#12]
- when closing gui screen freezes for a millisecond
- when pressing tab mc crashes

**Comment by TrvsF** [comment]
unsure about the tab crash thing, what other clients are you using?

**Comment by wallhackz** [comment]
i got the tab crash too i use it with pyro and phobos

**Comment by zispanos** [comment]
i love u travis

**Comment by kylerittenhause** [comment]
should be fixed rn

**Comment by TrvsF** [comment]
its a feature, love you too zispanos x
