### ISSUE TITLE
crystal aura rubberbanding

### ISSUE THREAD

**Issue by beepbeepnotajeep** [TrvsF/wurstplus-two#15]
the client works great other then the fact that my crystal aura settings are rubberbanding me back if you can help me then that would be great

**Comment by NathanW-Main** [comment]
Its probably your settings, Id keep playing around with them. Might be another module so just check all your clients and keybinds

**Comment by DaisyD2** [comment]
turn off crits

**Comment by TrvsF** [comment]
see above
