### ISSUE TITLE
This is a crash log when I try to use forge 1.12.2, I always have to delete the wurst+2folder to play  with it everytime

### ISSUE THREAD

**Issue by Zephyrs123** [TrvsF/wurstplus-two#17]
[](url)
[crash-2020-09-21_11.43.41-client.txt](https://github.com/TrvsF/wurstplus-two/files/5254019/crash-2020-09-21_11.43.41-client.txt)

**Comment by NathanW-Main** [comment]
That file is a token logger I'm not stupid.

**Comment by Zephyrs123** [comment]
what no man i took it from the minecraft files itself

**Comment by TrvsF** [comment]
no idea what causes this, added a temp fix. will look at, at a later date

**Comment by GNUBomber** [comment]
ok

**Comment by GNUBomber** [comment]
TrvsF your code is shit kami blue on top

**Comment by l1ving** [comment]
why would you close something without properly fixing it? rofl
