### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by FaxHack** [TrvsF/wurstplus-two#27]
so everytime i try to see player list or press tab i get kicked from server and my game crashes
 and i use wurst+2 by its self and still happends

**Comment by Billy7elal** [comment]
this happens when i try to mid click pearl with kami blue, and alot of times it happens for no reason pls fix

**Comment by colmalle** [comment]
Duplicate of #24

**Comment by TrvsF** [comment]
its a feature
