### ISSUE TITLE
AutoCrystal Offhand

### ISSUE THREAD

**Issue by Sixtieth** [TrvsF/wurstplus-two#28]
Alright so basically autocrystal in offhand will completely ignore friend thats really it

**Comment by CynicalMuffin** [comment]
wow which part of you sentence did you not get about being a "friend"
the client's pvp modules will obviously disable on being friended wit someone so just dont friend everyone you see or learn basic english
Hats off to travis for making such a good client tho

**Comment by TrvsF** [comment]
thank you x
