### ISSUE TITLE
Prefix bug

### ISSUE THREAD

**Issue by jndcmkxoikfjdcmxk** [TrvsF/wurstplus-two#29]

**Comment by MCTV1** [comment]
When I open shulker or a chest the inventory is red.
![Uploading 1122830E-188E-43A7-80B4-CAA4776EDE9D.jpeg…]()

**Comment by MCTV1** [comment]
![09636865-B2EB-40C5-B9DF-D50EC413F6E5](https://user-images.githubusercontent.com/72360648/95027344-0befe980-0698-11eb-8da4-c25ca0510b4e.jpeg)
