### ISSUE TITLE
Anchor or Fastfall

### ISSUE THREAD

**Issue by Avocado765** [TrvsF/wurstplus-two#34]
This is not a issue, but a feature that would make the client way better. Anchor is better, but the Fastfall would be ok too.

**Comment by sixtiethh** [comment]
Your so fucking retarded If you cant take the time out of your day to even 1 look at the new commits and 2 step is already in the 1.0 version it's in many clients it's a option under step anchor and reverse step are both already in the client just travis doesnt have a prebuilt jar for the newer commits.

**Comment by Fex47** [comment]
Holy shit retard figure out how to build a jar
