### ISSUE TITLE
singleplayer in runClient crashes and build run from launcher isnt working

### ISSUE THREAD

**Issue by kylerittenhause** [TrvsF/wurstplus-two#38]
i can only run runClient from source, singleplayer in runClient crashes and the jar from `./gradlew build` doesn't work and crashes

**Comment by tupi404040** [comment]
> i can only run runClient from source, singleplayer in runClient crashes and the jar from `./gradlew build` doesn't work and crashes
TUPI TUPI TUPI

**Comment by GNUBomber** [comment]
no idea what causes this, added a temp fix. will look at, at a later date.

> TrvsF closed this 22 days ago
