### ISSUE TITLE
Please Rewrite the Crystal Aura

### ISSUE THREAD

**Issue by AiryXV** [TrvsF/wurstplus-two#39]
Hello Travis can you please re wite the crystal aura code cause it sucks really bad it dosen't place through walls + it never places ahead of the player in a hole those features would be cool

**Comment by linustouchtips** [comment]
not only are you very wrong, he is def not going to rewrite the ca cause you have a bad config

**Comment by Fex47** [comment]
Yes tavgis pzlzzz rewqgrite wutsr++23 ur 
crgstal agrua iss tertgifblre1!1!2!!22!22'

**Comment by apollo365** [comment]
i can almost guarentee you use pyro ca
