### ISSUE TITLE
CustomViewmodel isnt kind to me :(

### ISSUE THREAD

**Issue by 25iscool** [TrvsF/wurstplus-two#4]
![image](https://user-images.githubusercontent.com/67598574/93404934-7ecd2800-f883-11ea-9b0c-30e9e3dab9b0.png)

**Comment by 25iscool** [comment]
some bitch square shit on my screen

**Comment by LilN1gger** [comment]
#

**Comment by 465ww** [comment]
why are u so ugly wtf

**Comment by TrvsF** [comment]
the square is the water overlay, its just not overlapping fully because you player camera's fov is larger than normal
