### ISSUE TITLE
where'd you go travis?

### ISSUE THREAD

**Issue by ghost** [TrvsF/wurstplus-two#40]
seem to have disappeared

**Comment by linustouchtips** [comment]
agreed, very sad :(

**Comment by Elementars** [comment]
:)

**Comment by TrvsF** [comment]
dead, also ele the only thing you did was get all ur mates token logged :D

**Comment by Elementars** [comment]
they ran it before I checked it, don't get your panties in a twist Mr. F!

**Comment by TrvsF** [comment]
apologies mr g

**Comment by Crystallinqq** [comment]
this is pretty funny.
