### ISSUE TITLE
Playerlist opening crash

### ISSUE THREAD

**Issue by Prithium** [TrvsF/wurstplus-two#49]
I know this has been covered 3 times, although one solution was to build the code because the fix was already committed, I don't know how to build the code though. So how do I build the code?

**Comment by ya-ilya** [comment]
https://github.com/colmalle/WurstPlusTwo-fix/releases/download/V1.0/wurstplus-two-fix.jar  try using this version

**Comment by TrvsF** [comment]
google how to build a gradle project
