### ISSUE TITLE
Game crashes when i walk

### ISSUE THREAD

**Issue by Stawberrymind** [TrvsF/wurstplus-two#50]
The game crashed whilst unexpected error Error: java.lang.IndexOutOfBoundsException: toIndex = 255 Exit Code: -1
@TrvsF 
Pls help 👍

**Comment by colmalle** [comment]
I'm pretty sure it's because you opened your player list. it has been fixed, you just have to build it yourself.

**Comment by CynicalMuffin** [comment]
as for the player list i never had a crash even with the older versions so ill assume its something to do with one of your mods if the crash still occours.

**Comment by TrvsF** [comment]
send logs or build urself
