### ISSUE TITLE
Just some general things that should be done to this repo

### ISSUE THREAD

**Issue by anonfoxer** [TrvsF/wurstplus-two#52]
I like the dry humor in the Repo, but I feel like the README should include more information because it isn't exactly clear.

In partiuclar:
The fact that it is a Forge mod.
What version of the game it's for

That's all. Otherwise pretty based.

**Comment by choose-a-new-name** [comment]
2nd one is good 1st one should be obvious

**Comment by choose-a-new-name** [comment]
> 
> 
> 2nd one is good 1st one should be obvious

[nevermind](https://github.com/TrvsF/wurstplus-two/issues/45)

**Comment by TrvsF** [comment]
mite do it later
