### ISSUE TITLE
issue with start

### ISSUE THREAD

**Issue by LSBsandbar** [TrvsF/wurstplus-two#60]
I am very new to this and I don't know what version of Minecraft it works on or if it runs off of forge or fabric. I also don't know how to work it in general. I would very much appreciate a walkthrough on how to do it. sorry for asking a lot. thanks

**Comment by maxgamesNL** [comment]
Most of the hacks work on forge(so does this one) 1.12.2

**Comment by LSBsandbar** [comment]
thanks
