### ISSUE TITLE
New features (didn’t know where else to put them)

### ISSUE THREAD

**Issue by psychosquirrel42** [TrvsF/wurstplus-two#62]
I think it would be a good idea to add something similar too anchor from pyro client where when you go overtop of a hole on in crystal pvp it will stop your movement so you fall into the hole and you won’t get crystaled just trying to walk into a hole

**Comment by psychosquirrel42** [comment]
Also if there is a different place to post something like this please tell me

**Comment by TrvsF** [comment]
no
