### ISSUE TITLE
pressing tab crashes my game

### ISSUE THREAD

**Issue by AppleInTheFridge** [TrvsF/wurstplus-two#69]
fit it

**Comment by tomiiiiiiiii** [comment]
Yeah, please fix it.

**Comment by ObsidianBreaker** [comment]
That's already fixed

**Comment by SnippitCoder** [comment]
This already has been fixed but has not been released in the releases tab. Compile it on your own and the bug should be gone.

**Comment by OCDkirby** [comment]
@Zahtec I'd like to compile it myself, but the gradlew.bat is giving me errors about not being able to connect to the Maven server. Can you give some more detailed instructions on how to compile from source? Perhaps make a pull request for the readme?

**Comment by NotADinosaur** [comment]
Go to the build.gradle and replace any links that start with http:// with https://

**Comment by OCDkirby** [comment]
@NotADinosaur compiled successfully, but where does the artifact output to? I can't find it in the repo folder (I searched 'file:*.jar').

**Comment by NotADinosaur** [comment]
`root\build\libs`

**Comment by OCDkirby** [comment]
@NotADinosaur The only folder I have in the build folder is tmp, which contains the empty folder compileJava and nothing else.

**Comment by Zahtec** [comment]
Open command prompt
Cd to the folder
Do `gradlew build`
Should be in `./build/libs`, Make sure you use the one ending in `-all`

**Comment by happyspeler** [comment]
Maybe if you use GameSense disable it

**Comment by TrvsF** [comment]
its a feature
