### ISSUE TITLE
Im dumb arent i? How do i download it?

### ISSUE THREAD

**Issue by IdkWhatToNameMyselfe** [TrvsF/wurstplus-two#72]
How do i download this it may sound dum?

**Comment by tman10001** [comment]
whats your discord?

**Comment by IdkWhatToNameMyselfe** [comment]
I dont have discord i just wanna know what i need to have it installed.

**Comment by IdkWhatToNameMyselfe** [comment]
> whats your discord?

I dont have discord i just need to know what i need for it.

**Comment by tman10001** [comment]
bruh are you autistic https://github.com/TrvsF/wurstplus-two/releases/tag/v1.0 you could litellary have pressed on the releases tab and got it

**Comment by IdkWhatToNameMyselfe** [comment]
> bruh are you autistic https://github.com/TrvsF/wurstplus-two/releases/tag/v1.0 you could litellary have pressed on the releases tab and got it

I see that but it opens a java thingy. What do I do with that?

**Comment by IdkWhatToNameMyselfe** [comment]
> bruh are you autistic https://github.com/TrvsF/wurstplus-two/releases/tag/v1.0 you could litellary have pressed on the releases tab and got it

Nvm got it
