### ISSUE TITLE
huge dummy need help

### ISSUE THREAD

**Issue by kono7** [TrvsF/wurstplus-two#73]
how do i compile the src? when i do gradlew build in the folder it says it fails

**Comment by YeahOMA** [comment]
ur mom rofl

**Comment by kono7** [comment]
😢😢😢😢😢

**Comment by JustBeyz** [comment]
Ur mom

**Comment by TrvsF** [comment]
https://github.com/Gopro336/PSA-how-to-fix-gradle-builds-feb-2021
