### ISSUE TITLE
MALWHARE

### ISSUE THREAD

**Issue by Enderboyscool** [TrvsF/wurstplus-two#76]
What happend with you and phobos and malwhare

**Comment by NotADinosaur** [comment]
LMFAO

**Comment by Enderboyscool** [comment]
stfu crystal link btw

**Comment by TrvsF** [comment]
how do i pin an issue?

**Comment by Enderboyscool** [comment]
You can just not put a virus on it

**Comment by Enderboyscool** [comment]
like we all know it has a virus if you watch  Wifies

**Comment by Enderboyscool** [comment]
was it because of phobos

**Comment by TrvsF** [comment]
i literally went through and closed every other issue because this one made me laugh so much, thank you for existing

**Comment by Enderboyscool** [comment]
wait

**Comment by Enderboyscool** [comment]
does it still have a virus

**Comment by TrvsF** [comment]
turns out you edited the original post, thats upsetting :(

**Comment by Enderboyscool** [comment]
sorry

**Comment by Enderboyscool** [comment]
I wana know does it still have a virus also why did you add one

**Comment by TrvsF** [comment]
and no, it doesnt, the version with a 'virus' was only ever sent to one person, and not by me

**Comment by Enderboyscool** [comment]
wait it was

**Comment by Enderboyscool** [comment]
where was the sorce code virus'

**Comment by Enderboyscool** [comment]
I wana know if its safe

**Comment by TrvsF** [comment]
um, i think you want this? https://github.com/TrvsF/discord-token-logger

**Comment by Enderboyscool** [comment]
Thanks

**Comment by 25iscool** [comment]
Noooo he closed it 😭

**Comment by TrvsF** [comment]
please do not close the issue

**Comment by Madmegsox1** [comment]
lets goooo

**Comment by Enderboyscool** [comment]
also can I have a private hack client

**Comment by Enderboyscool** [comment]
anywhere to dm u

**Comment by TrvsF** [comment]
no

**Comment by 3s0** [comment]
> no

rude

**Comment by Enderboyscool** [comment]
like are u still  working on it

**Comment by TrvsF** [comment]
https://github.com/TrvsF/wurstplus-two/issues/80#issuecomment-801473766

**Comment by phobologicalt** [comment]
omg this is amazing

**Comment by cgi-op** [comment]
was just wondering but how would you download this on Mac

**Comment by phobologicalt** [comment]
> was just wondering but how would you download this on Mac 
ask someone on discord to build it for you or use the outdated one in releases

**Comment by cgi-op** [comment]
> was just wondering but how would you download this on Mac
> ask someone on discord to build it for you or use the outdated one in releases

ok

**Comment by cgi-op** [comment]
although not the reason why im asking for help

**Comment by cgi-op** [comment]
> was just wondering but how would you download this on Mac
> ask someone on discord to build it for you or use the outdated one in releases

you see I asked, about like, do I just put it in the mods folder, or what

**Comment by phobologicalt** [comment]
> > was just wondering but how would you download this on Mac
> > ask someone on discord to build it for you or use the outdated one in releases
> 
> you see I asked, about like, do I just put it in the mods folder, or what

yes just drop it into the mods folder of 1.12.2 forge

**Comment by phobologicalt** [comment]
> > > > was just wondering but how would you download this on Mac
> > > > ask someone on discord to build it for you or use the outdated one in releases
> > > 
> > > 
> > > you see I asked, about like, do I just put it in the mods folder, or what
> > 
> > 
> > yes just drop it into the mods folder of 1.12.2 forge
> 
> ok thanks will fo later when I reinstall Minecraft (my little brother went through it and started randomly deleting shit)

I love how at one point it was someone blaming travis for malware now its so random NN trying to give support lmao

**Comment by cgi-op** [comment]
> > > > > was just wondering but how would you download this on Mac
> > > > > ask someone on discord to build it for you or use the outdated one in releases
> > > > 
> > > > 
> > > > you see I asked, about like, do I just put it in the mods folder, or what
> > > 
> > > 
> > > yes just drop it into the mods folder of 1.12.2 forge
> > 
> > 
> > ok thanks will fo later when I reinstall Minecraft (my little brother went through it and started randomly deleting shit)
> 
> I love how at one point it was someone blaming travis for malware now its so random NN trying to give support lmao

true

**Comment by 25iscool** [comment]
The quality of this thread was gold. But its bad now, which upsets me deeply

**Comment by cgi-op** [comment]
> The quality of this thread was gold. But its bad now, which upsets me deeply

you are an arrogant prick, this deeply upsets me

**Comment by TrvsF** [comment]
https://github.com/TrvsF/wurstplus-two/issues/76#issuecomment-803029177
i agree

**Comment by Nuker4** [comment]
FUCK MAN

**Comment by 4w2** [comment]
THE IQ OF THIS ISSUE IS FUNNY

**Comment by DankDupe** [comment]
i love this.
