### ISSUE TITLE
VIRUS

### ISSUE THREAD

**Issue by typica1** [TrvsF/wurstplus-two#82]
THE GUY THAT MAKE THIS IS VIRUS HE PUT MALWHARE IN IT HE IS LIEING IN THE OTHER POST STOP DOWNLOADING IT IS MALWHARE AND VIRUS IT WILL HACK YOUR COMPUTER THE WIFIES VIDEO EVEN SAID IT HE TAKE IT DOWN BCUS HE IS MAD HE IS GRAB YOUR INFO HE IS LIEING TO U IT VIRUS!!!!!!!!!!!

**Comment by typica1** [comment]
IF TRFVS CLOSE THIS HE IS A LIER HE IS STUPID IDIOT LIER HE IS MOTHERFUCK SHIT BITCH

**Comment by phobologicalt** [comment]
omg this is amazing @TrvsF  you gotta see this

**Comment by TrvsF** [comment]
on the off chance this isnt a troll heres what wifies had to say after we spoke : https://gyazo.com/f95999aca7387e7a8ded129d24da959d 
also if you dont think the jar is safe please build it yourself
