### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by giedrius07** [TrvsF/wurstplus-two#85]
Hello i have an issue when i open GUI it is zoomed in and i cannot zoom out and i cannot change a lot of settings bc i cant press

**Comment by giedrius07** [comment]
> Hello i have an issue when i open GUI it is zoomed in and i cannot zoom out and i cannot change a lot of settings bc i cant press

![2021-03-19_20 52 36](https://user-images.githubusercontent.com/80982015/111829210-1247ea00-88f5-11eb-904f-2c7553297263.png) This is what i see

**Comment by TrvsF** [comment]
https://github.com/TrvsF/wurstplus-two/issues/80#issuecomment-801473766

**Comment by ProfKambing** [comment]
BRUH JUST CHANGE UR GUI SCALE FFS TRAVIS THEY'RE KIDS
