### ISSUE TITLE
FIX THE TAB BUTTON

### ISSUE THREAD

**Issue by MegaloGuy1** [TrvsF/wurstplus-two#89]
Hi, TrvsF, can you please fix the tab crashing issue? Everytime I press tab, it crashes my game, please fix that.
Thank you! :)

**Comment by phobologicalt** [comment]
bro this client hasnt been properly worked on in 6+ months

**Comment by phobologicalt** [comment]
also someone else had the same issue, just build the newest version.

**Comment by phobologicalt** [comment]
https://github.com/TrvsF/wurstplus-two/issues/88#issuecomment-804517493
