### ISSUE TITLE
auto32k doesnt work 

### ISSUE THREAD

**Issue by UttamOnTop** [TrvsF/wurstplus-two#91]
it doesnt work when you are trying to use dispensers. It doesnt put the kit into the dispenser. it also doesnt place the hopper.

**Comment by PythonJoshua** [comment]
> it doesnt work when you are trying to use dispensers. It doesnt put the kit into the dispenser. it also doesnt place the hopper.

config issue

**Comment by TrvsF** [comment]
^ from what i can remember turning up the delay should work
